# Generated by Django 6.0.7 on 2026-07-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Order Confirmed'), ('shipping', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
